### ISSUE TITLE
 Using removed Babel 5 option: base.optional

### ISSUE THREAD

**Issue by bdcwq** [wssgcg1213/koa2-react-isomorphic-boilerplate#34]
当我执行npm run dev的时候报这个错误。。

Waiting for webpacking ...
/Users/bjcwq/Develop/project/weifriend/src/WeiFriendWebApp/node_modules/babel-core/lib/transformation/file/logger.js:41
    throw new Constructor(this._buildMessage(msg));
    ^

ReferenceError: [BABEL] /Users/bjcwq/Develop/project/weifriend/src/WeiFriendWebApp/platforms/server/middlewareRegister.js: Using removed Babel 5 option: base.optional - Put the specific transforms you want in the `plugins` option
    at Logger.error (/Users/bjcwq/Develop/project/weifriend/src/WeiFriendWebApp/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/bjcwq/Develop/project/weifriend/src/WeiFriendWebApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:233:20)
    at OptionManager.init (/Users/bjcwq/Develop/project/weifriend/src/WeiFriendWebApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:383:12)
    at File.initOptions (/Users/bjcwq/Develop/project/weifriend/src/WeiFriendWebApp/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/Users/bjcwq/Develop/project/weifriend/src/WeiFriendWebApp/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/Users/bjcwq/Develop/project/weifriend/src/WeiFriendWebApp/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at Object.transformFileSync (/Users/bjcwq/Develop/project/weifriend/src/WeiFriendWebApp/node_modules/babel-core/lib/api/node.js:144:10)
    at compile (/Users/bjcwq/Develop/project/weifriend/src/WeiFriendWebApp/node_modules/babel-register/lib/node.js:120:20)
    at loader (/Users/bjcwq/Develop/project/weifriend/src/WeiFriendWebApp/node_modules/babel-register/lib/node.js:148:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/bjcwq/Develop/project/weifriend/src/WeiFriendWebApp/node_modules/babel-register/lib/node.js:158:7)

**Comment by wssgcg1213** [comment]
already fixed at https://github.com/wssgcg1213/koa2-react-isomorphic-boilerplate/commit/76a05a9e256d67a37af9130665b0fe10a2c41f00

please update to newest version instead   :)
